spring.application.name=travelportal
spring.mvc.servlet.path=/api
#server.port=${USERSERVICE_PORT}
server.port=8080

#Info
info.app.name=Travel Portal 
info.app.description=Travel Portal by Akshat R
#info.app.version=${USERSERVICE_VERSION}

#Database
spring.datasource.url=jdbc:mysql://localhost:3306/travelportal
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Actuaor
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.endpoint.shutdown.enabled=true
server.shutdown=graceful

#Security
jwt.secret.key=Pkhzj9g2h6+0a7lV5f0hR9lD2Q7FJxR8M0Q5w7t8J6xYVvM2dP1eN4kLc8bQa0WJ
jwt.token.expiration=86400000
